app:
  util:
    username: ${USERNAME}
    password: ${PASSWORD}
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    properties:
      hibernate:
        dialect: ${DB_DIALECT}
    hibernate:
      ddl-auto: update